# Generated by Django 5.0.7 on 2024-07-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_strengthactivity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardioactivity",
            options={
                "ordering": ["-date", "exercise"],
                "verbose_name_plural": "Cardio activities",
            },
        ),
        migrations.AlterModelOptions(
            name="isometricactivity",
            options={
                "ordering": ["-date", "exercise"],
                "verbose_name_plural": "Isometric activities",
            },
        ),
    ]
