# Generated by Django 5.0.7 on 2024-07-29 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("Chest", "Chest"),
                            ("Back", "Back"),
                            ("Legs", "Legs"),
                            ("Glutes", "Glutes"),
                            ("Arms", "Arms"),
                            ("Shoulders", "Shoulders"),
                            ("Core", "Core"),
                        ],
                        max_length=150,
                    ),
                ),
            ],
            options={
                "ordering": ["muscle_group", "name"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Strength", "Strength"),
                            ("Isometric", "Isometric"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                ("equipment", models.ManyToManyField(blank=True, to="app.equipment")),
                (
                    "primary_muscle_focus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_exercises",
                        to="app.muscle",
                    ),
                ),
                (
                    "secondary_muscle_focus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_exercises",
                        to="app.muscle",
                    ),
                ),
            ],
            options={
                "ordering": ["type", "name"],
            },
        ),
    ]
