# Generated by Django 5.0.7 on 2024-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_muscle_muscle_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingplan",
            name="description",
            field=models.TextField(
                help_text="Description of the training plan that covers the main object of the plan."
            ),
        ),
        migrations.AlterField(
            model_name="trainingplan",
            name="name",
            field=models.CharField(
                help_text="Name of the training plan.", max_length=150
            ),
        ),
    ]
