# Generated by Django 5.0.7 on 2024-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_equipment_options_trainingplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingplan",
            name="exercises",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
