# Generated by Django 5.0.7 on 2024-07-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_trainingplan_exercises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="secondary_muscle_focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_exercises",
                to="app.muscle",
            ),
        ),
    ]
