# Generated by Django 5.0.7 on 2024-07-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_trainingschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingschedule",
            options={"ordering": ["-start_date"]},
        ),
    ]
