# Generated by Django 5.0.7 on 2024-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_cardioactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muscle",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("Chest", "Chest"),
                    ("Back", "Back"),
                    ("Legs", "Legs"),
                    ("Glutes", "Glutes"),
                    ("Arms", "Arms"),
                    ("Shoulders", "Shoulders"),
                    ("Core", "Core"),
                    ("Full Body", "Full Body"),
                ],
                max_length=150,
            ),
        ),
    ]
